FillZpp/sys-info-rs

- lib.rs
> Fix libc::sysctl missing on Windows builds

- lib.rs
The order of items in /proc/meminfo is not guaranteed to stay the same. It may change during Kernel Releases which will lead to errors in the parser.
> Parse /proc/meminfo using labels

- lib.rs
`libc::sysctl` is not available on musl. This PR fixes compilation error.
> Fix linux musl compilation

- c/linux.c
I ran into some undefined behavior where the library would return nonsensical values (usually capping at std::u64::MAX) because we'd would be treading into uninitialized memory since dtotal and dfree weren't initialized.
> Initializing dtotal and dfree to avoid undefined behavior

- lib.rs
Test on Windows native was failing with:
```
error[E0425]: cannot find function `boottime` in this scope
--> lib.rs:415:18
|
415 |         let bt = boottime().unwrap();
|                  ^^^^^^^^ not found in this scope
```
This resolves it.
> Fix windows test.

- lib.rs
Closes: https://github.com/FillZpp/sys-info-rs/issues/43
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
> Cast gethostname() arguments to a proper type

- c/windows.c
For compatibility with libuv's `uv_os_uname()` function.
> include build number in os_release() on Windows

- README.md
This could trip newcomers. It's basically impossible to guarantee "my code will work with all versions of this crate", because major versions tend to break the interface. See https://semver.org/ for more information.
> Don't suggest to use glob version in the README

- c/windows.c
- lib.rs
This patch is in response to a couple of gcc warnings that occur for the x86_64-pc-windows-gnu target.  
I built for x86_64-unknown-linux-musl and x86_64-apple-darwin as well and didn't see any issues, but haven't tested other targets.
```
cargo build --target x86_64-pc-windows-gnu
Updating crates.io index
Compiling libc v0.2.67
Compiling cc v1.0.50
Compiling sys-info v0.5.10 (/g/rich/w/sys-info-rs/sys-info-rs)
warning: c/windows.c: In function ‘get_os_release’:
warning: c/windows.c:30:22: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘DWORD {aka long unsigned int}’ [-Wformat=]
warning:    snprintf(s, LEN, "%d.%d.%d",
warning:                      ~^
warning:                      %ld
warning:      osvi.dwMajorVersion, osvi.dwMinorVersion, …
```
> patch to resolve x86_64-pc-windows-gnu warnings

- CHANGELOG.md
- Cargo.toml
- README.md
- build.rs
- kstat.rs
- lib.rs
- test/src/main.rs
I have been working towards getting binaries for [illumos](https://illumos.org) (and presumably Solaris) systems into the official distribution channels used by `rustup`.  The `rustup` program itself makes use of the [effective-limits](https://crates.io/crates/effective-limits) crate, which in turn depends on this crate!  As part of my `rustup` porting effort, in this change I've added some basic illumos/Solaris support to **sys-info** itself.
Much of the information is available through our [kstat(3KSTAT)](https://illumos.org/man/3KSTAT/kstat) interface, which is somewhat analogous to BSD **sysctl(2)**.  The system library for kstat access, [libkstat(3LIB)](https://illumos.org/man/3LIB/libkstat), is considered a public, stable interface, so it's safe to use here in this way.  I've …
> support for illumos systems

- CHANGELOG.md
- Cargo.toml
- kstat.rs
- lib.rs
This minor change achieves two things:
* adds the reason that `kstat_open()` failed, if it did, to the error
* restores the `Send` trait to `sys_info::Error` by removing the boxed `Error` variant (mistakenly added in my prior change), so that it can still be wrapped by the [error-chain](https://crates.io/crates/error-chain) crate as used by [effective-limits](https://crates.io/crates/effective-limits)
With this change in place, I can get `effective-limits` to pass tests on illumos:
```
$ cargo test
Compiling cc v1.0.50
Compiling libc v0.2.67
Compiling sys-info v0.6.1 (/ws/sys-info-rs)
Finished test [unoptimized + debuginfo] target(s) in 3.96s
Running target/debug/deps/sys_info-fbc561f55e1cd210
running 9 tests
test test::test_cpu_num ... ok
test test::test_os_release ... ok
test …
```
> improve kstat error reporting

- c/macos.c
- kstat.rs
- lib.rs
- test/src/main.rs
There are a number of places where we use the cfg! macro today, but
unfortunately though convenient, that pattern does not completely
isolate conditional parts of the build.  This is particularly pertinent
on Windows, which lacks a lot of symbols that ordinarily appear in a
UNIX libc.
This change has been tested on at least:
* Mac OS X
* Windows 10
* Ubuntu 19.10
* illumos
There are no more compilation errors or warnings, and the program in
test/ appears work correctly.
> use cfg attribute instead of cfg! macro

- c/freebsd.c
- lib.rs
Mostly, these commits systematically return error instead of success with meaningless data for OS failures.  Also they fix small bugs in the port like type mismatch for non-64bit architectures.
> Freebsd port improvements

- .travis.yml
- lib.rs
Over at https://github.com/denoland/deno this crate is used to get info about the system.
As of denoland/deno#4496, one complaint has been that:
> sys-info is broken on Windows for 3 releases now, and doesn't have proper CI.
Therefore, following up on this, I have added a Window CI build to this repo.
Changes:
- Added windows CI build
- Travis' default toolchain is `_-x86_64-pc-windows-gnu`.  This has been swapped for `_-x86_64-pc-windows-msvc` since this crate uses windows headers.  This change has been documented in the CI YAML.
- Changed `#[cfg(linux)]` to `#[cfg(target_os = "linux")]` so `clippy` doesn't complain on rust beta builds
- I was going to change `cache: rust` to `cache: cargo` so cargo stuff can be cached, but this hangs the windows build.  It's a minor thing, however, and …
> Add Windows CI

- c/windows.c
`ullTotalPageFile` and `ullAvailPageFile` include both the swap and physical memory so in order to get the correct swap memory values the physical memory size/usage needs to be substracted.
https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-memorystatusex
> fix swap file calculation on windows

- build.rs
- c/windows.c
Instead of guessing the cpu speed based on performance counters query the system for the cpu speed without directly using any intel instructions. Presumably this will also make `get_cpu_speed ` more reliable.
I assume `get_cpu_speed` attempts to get the maximum clock speed because that's what the old version returned for me. If you want, I can add a loop over all the returned results and return the maximum or the value for the current cpu to better support heterogeneous architectures.
closes #68
> Make get_cpu_speed arch-independent on windows

- lib.rs
- test/src/main.rs
- Add privacy_policy_url field to `LinuxOSReleaseInfo`.
- Add methods to access fields, but taking the default values if no value was provided.
- Add doc comments to the fields.
> linux os-release: Add privacy_policy_url, methods for default values and doc comments.

- build.rs
- c/windows.c
Great to see that sys-info now compiles correctly on Windows arm64! This would help a lot to make rustup for Windows arm64 happen: https://github.com/rust-lang/rustup/issues/2612
Funnily enough, a few days ago I have prepared exactly the same solution to [make get_cpu_speed arm64-compatible on Windows](https://github.com/Alovchin91/sys-info-rs/commit/327928c3aa9c5925291ee07cd3bd784d9195add3) but I was too slow to open a PR 😅
However, the solution currently in master gives me the wrong result when running `cargo test -- --nocapture` on my Surface Pro X: `cpu_speed(): 1766`.
The reason is ARM's big.LITTLE architecture when the "efficiency" cores are listed first. We need to loop through the CPU cores to find the "actual" maximum CPU speed. Doing this I get the expected result: `cpu_speed(): …
> Loop to find max CPU speed in Windows get_cpu_speed

- c/macos.c
If sysctl fails with ENOMEM (because the buffer is too small), it will
set length to 0 (what I see) or to the length it actually copied (what
the man page says).
Regardless, this is not the length of the unknown value.
So instead of relying on `LEN` we tell `strncpy` the maximum it can
copy. It will add null bytes as necessary if that's too short.
If sysctl succeeded we can use that value.
Now the man page doesn't actually say so, but it seems it copies the
null byte reliably. Still, as I've seen no guarantee let's add a null
byte regardless.
As one last thing the intermediate buffer is unnecessary. It's the same
size as the dynamically allocated anyway and we copy between them. We
can get rid of it and write directly into our buffer.
---
I _think_ this is mostly theoretical because the …
> macOS: On failure copy the unknown value and null-terminate it correctly

- README.md
- build.rs
- c/netbsd.c
- lib.rs
The following commit adds support for the NetBSD platform.
This would also address the issue raised in #72
> Adds support for NetBSD platform.

- build.rs
- c/windows.c
This PR fixes sys-info building and linking on windows-gnu targets which prevents integrating the latest version into [effective-limits](https://github.com/rbtcollins/effective-limits.rs/pull/14) which in turn prevents building [rustup for Windows arm64](https://github.com/rust-lang/rustup/issues/2612).
> Fix windows-gnu build

- lib.rs
Fix for https://github.com/FillZpp/sys-info-rs/issues/98
I've round that implicit `return`s are best when trailing.
> Rust Nightly fix

- lib.rs
On architectures where `c_long` is an `i32`, e.g., OpenBSD/i386, the
comparison between `ret` and `u32::MAX as i64` is a type error.
Add a cast to satisfy the type checker on such architectures. This
cast is a noop on systems where `c_long` is an `i64`.
> Add a cast to allow building on ILP32 systems

- c/windows.c
In some circumstances `swap_free` (zero utilisation?) will end up larger than `swap_total`. To prevent this take the `swap_total` value for `swap_free` if `swap_free` is larger than `swap_total`.
The reason could  be because the `PageFile` and `Phys` values don't quite react the same to new allocations or because the `PageFile` values can either represent process or system level values.
> Prevent free swap from getting larger than total swap
